title: TomoDesign Works
logo: /assets/img/logo.svg
description: TomoDesign Worksは、地域文化の記録と発信を目的としたWebプロジェクトです。
url: https://ktctomcat.github.io
baseurl: ""
show_downloads: false
google_analytics: false
lang: ja
theme: jekyll-theme-minimal

# グローバルナビゲーションの設定
header_pages:
  - index.md 
  - works.md
  - fragments.md

# OGP用アイコンの設定
defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/img/ogp.png