title: TomoDesign Works
logo: /assets/img/logo.svg
description: TomoDesign Worksは、構造に思想を宿すデザインを通じて、社会のゆらぎや文化の断片を静かに掬い取り、未来への記録として残します。
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
