title: TomoDesign Works
logo: /assets/img/logo.svg
favicon: /assets/img/favicon.ico
description: TomoDesign Worksは、構造に思想を宿すデザインを通じて、社会のゆらぎや文化の断片を静かに掬い取り、未来への記録として残します。
url: https://ktctomcat.github.io
show_downloads: true
google_analytics:
lamg: ja
theme: jekyll-theme-minimal
