title: TomoDesign Works
description: TomoDesign Worksは、地域文化の記録と発信を目的としたWebプロジェクトです。
url: https://ktctomcat.github.io
baseurl: ""
lang: ja
theme: jekyll-theme-minimal
logo: /assets/img/logo.svg
show_downloads: false
google_analytics: false

# 連絡先等の設定
author:
  name: Tomoo Ito
  email: ktc.tomcat@gmail.com
  twitter: ktc_tomcat
  github: ktctomcat
  instagram: ktc.tomcat
  facebook: ktc.tomcat

# グローバルナビゲーションの設定
header_pages:
  - index.md 
  - works.md
  - fragments.md

# OGP用アイコンの設定
defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/img/ogp.png
