title: TomoDesign Works
logo: /assets/img/logo.svg
favicon: /assets/img/favicon.ico
description: TomoDesign Worksは、構造に思想を宿すデザインを通じて、社会のゆらぎや文化の断片を静かに掬い取り、未来への記録として残しています。
url: https://ktctomcat.github.io
baseurl: ""
show_downloads: false
google_analytics: false
lang: ja
theme: jekyll-theme-minima

# グリーバルナビゲーションの設定
header_pages:
  - index.md 
  - works.md
  - fragments.md

# OGP用アイコンの設定
defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/img/ogp.png