title: TomoDesign Works
logo: /assets/img/logo.svg
favicon: /assets/img/favicon.ico
description: TomoDesign Worksは、構造に思想を宿すデザインを通じて、社会のゆらぎや文化の断片を静かに掬い取り、未来への記録として残しています。
url: https://ktctomcat.github.io
baseurl: ""
show_downloads: true
google_analytics: false
lang: ja
theme: jekyll-theme-minimal
header_pages:
  - index.md 
  - works.md
  - fragments.md
  - about.md